# Generated by Django 4.1.5 on 2023-03-03 01:15

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zubdarg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', hashid_field.field.BigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=13, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'unique_together': {('word', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', hashid_field.field.BigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=13, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zubdarg.page')),
            ],
            options={
                'unique_together': {('reference_id', 'version')},
            },
        ),
    ]
