# Generated by Django 4.1.7 on 2023-03-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zubdarg', '0001_initial'),
        ('lakharg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='reference_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zubdarg.page'),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('reference_id', 'version')},
        ),
    ]
