version: '3.7'

services:
  django:
    container_name: ce-corpora-django
    build:
      context: ./backend
    restart: unless-stopped
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    command: >
      bash -c "python manage.py migrate
      && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - ALLOWED_HOSTS
      - APPWRITE_PROJECT_API_KEY
      - APPWRITE_PROJECT_ENDPOINT
      - APPWRITE_PROJECT_ID
      - CORS_ALLOWED_ORIGINS
      - CORS_ALLOW_CREDENTIALS
      - CORS_ALLOW_HEADERS
      - CSRF_COOKIE_HTTPONLY
      - CSRF_COOKIE_NAME
      - CSRF_COOKIE_SAMESITE
      - CSRF_COOKIE_SECURE
      - DB_ENGINE
      - DB_HOST
      - DB_NAME
      - DB_PASSWORD
      - DB_PORT
      - DB_SSL_MODE
      - DB_USER
      - DEBUG
      - DJANGO_SETTINGS_MODULE
      - HASHID_FIELD_SALT
      - PYTHONDONTWRITEBYTECODE
      - PYTHONUNBUFFERED
      - SECRET_KEY
      - SESSION_COOKIE_HTTPONLY
      - SESSION_COOKIE_SAMESITE
      - SESSION_COOKIE_SECURE
    expose:
      - 8000
    networks:
      - web
  nginx:
    container_name: ce-corpora-nginx
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    ports:
      - '8090:80'
    networks:
      - web
    depends_on:
      - django

volumes:
  staticfiles:
  mediafiles:

networks:
  web:
    external: true
