version: '3.7'

services:
  django:
    container_name: ce-corpora-django
    build:
      context: ./backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE}-api.rule=(Host(`${DOMAIN_NAME}`) && PathPrefix(`/api`))"
      - "traefik.http.routers.${SERVICE}-api.entrypoints=web-secure"
      - "traefik.http.routers.${SERVICE}-api.tls.certresolver=letsEncrypt"
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    command: >
      bash -c "python manage.py migrate
      && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    env_file: ./backend/.env
    expose:
      - 8000
    networks:
      - web
  nginx:
    container_name: ce-corpora-nginx
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE}-client.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${SERVICE}-client.entrypoints=web-secure"
      - "traefik.http.routers.${SERVICE}-client.tls.certresolver=letsEncrypt"
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    expose:
      - 80
    networks:
      - web
    depends_on:
      - django

volumes:
  staticfiles:
  mediafiles:

networks:
  web:
    external: true
